version: '3'

services:
  app: 
    container_name: nestjs-app
    build: .
    depends_on:
      - db
  db:
    image: 'postgres:16'
    container_name: nestjs-app-postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}